SELECT 
    recent_team,
    season, 
    season_type, 
    week, 
    (SUM(rushing_tds) + SUM(receiving_tds) + SUM(special_teams_tds)) * 6 as touchdown_points, 
    SUM(rushing_tds) + SUM(receiving_tds) + SUM(special_teams_tds) as touchdowns_scored, 
    SUM(passing_yards) as passing_yards, 
    SUM(rushing_yards) as rushing_yards, 
    SUM(receiving_yards) as receiving_yards, 
    SUM(passing_tds) as passing_tds, 
    SUM(rushing_tds) as rushing_tds, 
    SUM(receiving_tds) as receiving_tds,
    SUM(special_teams_tds) as special_teams_tds,
    SUM(interceptions) as interceptions, 
    SUM(sacks) as sacks, 
    SUM(rushing_fumbles) as rushing_fumbles, 
    SUM(receiving_fumbles) as receiving_fumbles,
    SUM(rushing_first_downs) as rushing_first_downs,
    SUM(receiving_first_downs) as receiving_first_downs,
    SUM(carries) as carries, 
    SUM(targets) as targets, 
    SUM(receptions) as receptions, 
    SUM(passing_2pt_conversions) as passing_2pt_conversions,
    SUM(rushing_2pt_conversions) as rushing_2pt_conversions,
    SUM(receiving_2pt_conversions) as receiving_2pt_conversions, 
    SUM(completions) as completions, 
    SUM(attempts) as attempts, 
    SUM(sack_yards) as sack_yards, 
    SUM(sack_fumbles) as sack_fumbles, 
    SUM(sack_fumbles_lost) as sack_fumbles_lost, 
    SUM(passing_air_yards) as passing_air_yards, 
    SUM(passing_yards_after_catch) as passing_yards_after_catch, 
    SUM(passing_first_downs) as passing_first_downs, 
    SUM(rushing_fumbles_lost) as rushing_fumbles_lost,
    SUM(receiving_fumbles_lost) as receiving_fumbles_lost,
    SUM(receiving_air_yards) as receiving_air_yards,
    SUM(receiving_yards_after_catch) as receiving_yards_after_catch
FROM stg_weekly_scores
GROUP BY 
    recent_team, 
    SEASON, 
    season_type, 
    week; 